remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Coral Stewart ePortfolio]
description: [For the past few weeks, I have been enhancing a piece of work from one of my previous computer science classes. A mobile weight-tracking app that previously had limited function, is now capable of storing user data, displaying summary statistics for weight and BMI, and is more secure. ]
